<?php

namespace App\Http\Requests\Domicilio;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class DomicilioRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
        
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        if ($this->isMethod('post')) {
            return $this->createRules();
        } elseif ($this->isMethod('put')) {
            return $this->updateRules();
        }
    }

    public function createRules(): array
    {
        return [


            'direccion'   => 'required|string|max:350',
            'numero'      => 'numeric|min:1|required',
            /*'region'      => ['required',
            Rule::in(['Región de Tarapacá',
            'Región de Antofagasta',
            'Región de Atacama',
            'Región de Coquimbo',
            'Región de Valparaiso',
            'Región del Libertador General Bernardo O\'Higgins',
            'Región del Maule',
            'Región del Biobío',
            'Región del La Araucanía',
            'Región del Los Lagos',
            'Región del Aisén del General Carlos Ibáñez del Campo',
            'Región del Magallanes y de la Antártica Chilena',
            'Región Metropolitana de Santiago',
            'Región de Los Ríos',
            'Región de Arica y Parinacota',
            'Región de Ñuble',]),],*/
            'comuna'      => ['required',
            Rule::in(['Arica',
            'Camarones',
            'General Lagos',
            'Putre',
            'Alto Hospicio',
            'Iquique',
            'Camiña',
            'Colchane',
            'Huara',
            'Pica',
            'Pozo Almonte',
            'Antofagasta',
            'Mejillones',
            'Sierra Gorda',
            'Taltal',
            'Calama',
            'Ollague',
            'San Pedro de Atacama',
            'María Elena',
            'Tocopilla',
            'Chañaral',
            'Diego de Almagro',
            'Caldera',
            'Copiapó',
            'Tierra Amarilla',
            'Alto del Carmen',
            'Freirina',
            'Huasco',
            'Vallenar',
            'Canela',
            'Illapel',
            'Los Vilos',
            'Salamanca',
            'Andacollo',
            'Coquimbo',
            'La Higuera',
            'La Serena',
            'Paihuaco',
            'Vicuña',
            'Combarbalá',
            'Monte Patria',
            'Ovalle',
            'Punitaqui',
            'Río Hurtado',
            'Isla de Pascua',
            'Calle Larga',
            'Los Andes',
            'Rinconada',
            'San Esteban',
            'La Ligua',
            'Papudo',
            'Petorca',
            'Zapallar',
            'Hijuelas',
            'La Calera',
            'La Cruz',
            'Limache',
            'Nogales',
            'Olmué',
            'Quillota',
            'Algarrobo',
            'Cartagena',
            'El Quisco',
            'El Tabo',
            'San Antonio',
            'Santo Domingo',
            'Catemu',
            'Llaillay',
            'Panquehue',
            'Putaendo',
            'San Felipe',
            'Santa María',
            'Casablanca',
            'Concón',
            'Juan Fernández',
            'Puchuncaví',
            'Quilpué',
            'Quintero',
            'Valparaíso',
            'Villa Alemana',
            'Viña del Mar',
            'Colina',
            'Lampa',
            'Tiltil',
            'Pirque',
            'Puente Alto',
            'San José de Maipo',
            'Buin',
            'Calera de Tango',
            'Paine',
            'San Bernardo',
            'Alhué',
            'Curacaví',
            'María Pinto',
            'Melipilla',
            'San Pedro',
            'Cerrillos',
            'Cerro Navia',
            'Conchalí',
            'El Bosque',
            'Estación Central',
            'Huechuraba',
            'Independencia',
            'La Cisterna',
            'La Granja',
            'La Florida',
            'La Pintana',
            'La Reina',
            'Las Condes',
            'Lo Barnechea',
            'Lo Espejo',
            'Lo Prado',
            'Macul',
            'Maipú',
            'Ñuñoa',
            'Pedro Aguirre Cerda',
            'Peñalolén',
            'Providencia',
            'Pudahuel',
            'Quilicura',
            'Quinta Normal',
            'Recoleta',
            'Renca',
            'San Miguel',
            'San Joaquín',
            'San Ramón',
            'Santiago',
            'Vitacura',
            'El Monte',
            'Isla de Maipo',
            'Padre Hurtado',
            'Peñaflor',
            'Talagante',
            'Codegua',
            'Coínco',
            'Coltauco',
            'Doñihue',
            'Graneros',
            'Las Cabras',
            'Machalí',
            'Malloa',
            'Mostazal',
            'Olivar',
            'Peumo',
            'Pichidegua',
            'Quinta de Tilcoco',
            'Rancagua',
            'Rengo',
            'Requínoa',
            'San Vicente de Tagua Tagua',
            'La Estrella',
            'Litueche',
            'Marchihue',
            'Navidad',
            'Peredones',
            'Pichilemu',
            'Chépica',
            'Chimbarongo',
            'Lolol',
            'Nancagua',
            'Palmilla',
            'Peralillo',
            'Placilla',
            'Pumanque',
            'San Fernando',
            'Santa Cruz',
            'Cauquenes',
            'Chanco',
            'Pelluhue',
            'Curicó',
            'Hualañé',
            'Licantén',
            'Molina',
            'Rauco',
            'Romeral',
            'Sagrada Familia',
            'Teno',
            'Vichuquén',
            'Colbún',
            'Linares',
            'Longaví',
            'Parral',
            'Retiro',
            'San Javier',
            'Villa Alegre',
            'Yerbas Buenas',
            'Constitución',
            'Curepto',
            'Empedrado',
            'Maule',
            'Pelarco',
            'Pencahue',
            'Río Claro',
            'San Clemente',
            'San Rafael',
            'Talca',
            'Arauco',
            'Cañete',
            'Contulmo',
            'Curanilahue',
            'Lebu',
            'Los Álamos',
            'Tirúa',
            'Alto Biobío',
            'Antuco',
            'Cabrero',
            'Laja',
            'Los Ángeles',
            'Mulchén',
            'Nacimiento',
            'Negrete',
            'Quilaco',
            'Quilleco',
            'San Rosendo',
            'Santa Bárbara',
            'Tucapel',
            'Yumbel',
            'Chiguayante',
            'Concepción',
            'Coronel',
            'Florida',
            'Hualpén',
            'Hualqui',
            'Lota',
            'Penco',
            'San Pedro de La Paz',
            'Santa Juana',
            'Talcahuano',
            'Tomé',
            'Bulnes',
            'Chillán',
            'Chillán Viejo',
            'Cobquecura',
            'Coelemu',
            'Coihueco',
            'El Carmen',
            'Ninhue',
            'Ñiquen',
            'Pemuco',
            'Pinto',
            'Portezuelo',
            'Quillón',
            'Quirihue',
            'Ránquil',
            'San Carlos',
            'San Fabián',
            'San Ignacio',
            'San Nicolás',
            'Treguaco',
            'Yungay',
            'Carahue',
            'Cholchol',
            'Cunco',
            'Curarrehue',
            'Freire',
            'Galvarino',
            'Gorbea',
            'Lautaro',
            'Loncoche',
            'Melipeuco',
            'Nueva Imperial',
            'Padre Las Casas',
            'Perquenco',
            'Pitrufquén',
            'Pucón',
            'Saavedra',
            'Temuco',
            'Teodoro Schmidt',
            'Toltén',
            'Vilcún',
            'Villarrica',
            'Angol',
            'Collipulli',
            'Curacautín',
            'Ercilla',
            'Lonquimay',
            'Los Sauces',
            'Lumaco',
            'Purén',
            'Renaico',
            'Traiguén',
            'Victoria',
            'Corral',
            'Lanco',
            'Los Lagos',
            'Máfil',
            'Mariquina',
            'Paillaco',
            'Panguipulli',
            'Valdivia',
            'Futrono',
            'La Unión',
            'Lago Ranco',
            'Río Bueno',
            'Ancud',
            'Castro',
            'Chonchi',
            'Curaco de Vélez',
            'Dalcahue',
            'Puqueldón',
            'Queilén',
            'Quemchi',
            'Quellón',
            'Quinchao',
            'Calbuco',
            'Cochamó',
            'Fresia',
            'Frutillar',
            'Llanquihue',
            'Los Muermos',
            'Maullín',
            'Puerto Montt',
            'Puerto Varas',
            'Osorno',
            'Puero Octay',
            'Purranque',
            'Puyehue',
            'Río Negro',
            'San Juan de la Costa',
            'San Pablo',
            'Chaitén',
            'Futaleufú',
            'Hualaihué',
            'Palena',
            'Aisén',
            'Cisnes',
            'Guaitecas',
            'Cochrane',
            'O\'higgins',
            'Tortel',
            'Coihaique',
            'Lago Verde',
            'Chile Chico',
            'Río Ibáñez',
            'Antártica',
            'Cabo de Hornos',
            'Laguna Blanca',
            'Punta Arenas',
            'Río Verde',
            'San Gregorio',
            'Porvenir',
            'Primavera',
            'Timaukel',
            'Natales',
            'Torres del Paine',
            'Cabildo',]),],
            'obs'         => 'string|max:1000|nullable',
            'persona_id'  => 'required|integer|exists:personas,id',
        ];
    }

    public function updateRules(): array
    {
        return [

            'direccion'   => 'required|string|max:350|required',
            'numero'      => 'numeric|min:1|required',
            /*'region'      => ['required',
            Rule::in(['Arica y Parinacota','Tarapacá','Antofagasta','Atacama','Coquimbo','Valparaíso','Región del Libertador Gral. Bernardo O’Higgins',
            'Región del Maule','Región del Biobío','Región de la Araucanía','Región de Los Ríos','Región de Los Lagos','Región Aisén del Gral. Carlos Ibáñez del Campo',
            'Región de Magallanes y de la AntárVca Chilena','Región Metropolitana de Santiago',]),],*/
            'comuna'      => ['required',
            Rule::in(['Arica', 'Camarones', 'Putre', 'General Lagos',
            'Iquique', 'Alto Hospicio', 'Pozo Almonte', 'Camiña', 'Colchane', 'Huara', 'Pica',
            'Antofagasta', 'Mejillones', 'Sierra Gorda', 'Taltal', 'Calama', 'Ollagüe', 'San Pedro de Atacama', 'Tocopilla', 'María Elena',
            'Copiapó', 'Caldera', 'Tierra Amarilla', 'Chañaral', 'Diego de Almagro', 'Vallenar', 'Alto del Carmen', 'Freirina', 'Huasco',
            'La Serena', 'Coquimbo', 'Andacollo', 'La Higuera', 'Paiguano', 'Vicuña', 'Illapel', 'Canela', 'Los Vilos', 'Salamanca', 'Ovalle', 'Combarbalá', 'Monte Patria', 'Punitaqui', 'Río Hurtado',
            'Valparaíso', 'Casablanca', 'Concón', 'Juan Fernández', 'Puchuncaví', 'Quintero', 'Viña del Mar', 'Isla de Pascua', 'Los Andes', 'Calle Larga', 'Rinconada', 'San Esteban', 'La Ligua', 'Cabildo', 'Papudo', 'Petorca', 'Zapallar', 'Quillota', 'Calera', 'Hijuelas', 'La Cruz', 'Nogales', 'San Antonio', 'Algarrobo', 'Cartagena', 'El Quisco', 'El Tabo', 'Santo Domingo', 'San Felipe', 'Catemu', 'Llaillay', 'Panquehue', 'Putaendo', 'Santa María', 'Quilpué', 'Limache', 'Olmué', 'Villa Alemana',
            'Rancagua', 'Codegua', 'Coinco', 'Coltauco', 'Doñihue', 'Graneros', 'Las Cabras', 'Machalí', 'Malloa', 'Mostazal', 'Olivar', 'Peumo', 'Pichidegua', 'Quinta de Tilcoco', 'Rengo', 'Requínoa', 'San Vicente', 'Pichilemu', 'La Estrella', 'Litueche', 'Marchihue', 'Navidad', 'Paredones', 'San Fernando', 'Chépica', 'Chimbarongo', 'Lolol', 'Nancagua', 'Palmilla', 'Peralillo', 'Placilla', 'Pumanque', 'Santa Cruz',
            'Talca', 'ConsVtución', 'Curepto', 'Empedrado', 'Maule', 'Pelarco', 'Pencahue', 'Río Claro', 'San Clemente', 'San Rafael', 'Cauquenes', 'Chanco', 'Pelluhue', 'Curicó', 'Hualañé', 'Licantén', 'Molina', 'Rauco', 'Romeral', 'Sagrada Familia', 'Teno', 'Vichuquén', 'Linares', 'Colbún', 'Longaví', 'Parral', 'ReVro', 'San Javier', 'Villa Alegre', 'Yerbas Buenas',
            'Concepción', 'Coronel', 'Chiguayante', 'Florida', 'Hualqui', 'Lota', 'Penco', 'San Pedro de la Paz', 'Santa Juana', 'Talcahuano', 'Tomé', 'Hualpén', 'Lebu', 'Arauco', 'Cañete', 'Contulmo', 'Curanilahue', 'Los Álamos', 'Tirúa', 'Los Ángeles', 'Antuco', 'Cabrero', 'Laja', 'Mulchén', 'Nacimiento', 'Negrete', 'Quilaco', 'Quilleco', 'San Rosendo', 'Santa Bárbara', 'Tucapel', 'Yumbel', 'Alto Biobío', 'Chillán', 'Bulnes', 'Cobquecura', 'Coelemu', 'Coihueco', 'Chillán Viejo', 'El Carmen', 'Ninhue', 'Ñiquén', 'Pemuco', 'Pinto', 'Portezuelo', 'Quillón', 'Quirihue', 'Ránquil', 'San Carlos', 'San Fabián', 'San Ignacio', 'San Nicolás', 'Treguaco', 'Yungay',
            'Temuco', 'Carahue', 'Cunco', 'Curarrehue', 'Freire', 'Galvarino', 'Gorbea', 'Lautaro', 'Loncoche', 'Melipeuco', 'Nueva Imperial', 'Padre las Casas', 'Perquenco', 'Pitrufquén', 'Pucón', 'Saavedra', 'Teodoro Schmidt', 'Toltén', 'Vilcún', 'Villarrica', 'Cholchol', 'Angol', 'Collipulli', 'Curacautín', 'Ercilla', 'Lonquimay', 'Los Sauces', 'Lumaco', 'Purén', 'Renaico', 'Traiguén', 'Victoria',
            'Valdivia', 'Corral', 'Lanco', 'Los Lagos', 'Máfil', 'Mariquina', 'Paillaco', 'Panguipulli', 'La Unión', 'Futrono', 'Lago Ranco', 'Río Bueno',
            'Puerto Montt', 'Calbuco', 'Cochamó', 'Fresia', 'FruVllar', 'Los Muermos', 'Llanquihue', 'Maullín', 'Puerto Varas', 'Castro', 'Ancud', 'Chonchi', 'Curaco de Vélez', 'Dalcahue', 'Puqueldón', 'Queilén', 'Quellón', 'Quemchi', 'Quinchao', 'Osorno', 'Puerto Octay', 'Purranque', 'Puyehue', 'Río Negro', 'San Juan de la Costa', 'San Pablo', 'Chaitén', 'Futaleufú', 'Hualaihué', 'Palena',
            'Coihaique', 'Lago Verde', 'Aisén', 'Cisnes', 'Guaitecas', 'Cochrane', 'O’Higgins', 'Tortel', 'Chile Chico', 'Río Ibáñez',
            'Punta Arenas', 'Laguna Blanca', 'Río Verde', 'San Gregorio', 'Cabo de Hornos (Ex Navarino)', 'AntárVca', 'Porvenir', 'Primavera', 'Timaukel', 'Natales', 'Torres del Paine',
            'Cerrillos', 'Cerro Navia', 'Conchalí', 'El Bosque', 'Estación Central', 'Huechuraba', 'Independencia', 'La Cisterna', 'La Florida', 'La Granja', 'La Pintana', 'La Reina', 'Las Condes', 'Lo Barnechea', 'Lo Espejo', 'Lo Prado', 'Macul', 'Maipú', 'Ñuñoa', 'Pedro Aguirre Cerda', 'Peñalolén', 'Providencia', 'Pudahuel', 'Quilicura', 'Quinta Normal', 'Recoleta', 'Renca', 'San Joaquín', 'San Miguel', 'San Ramón', 'Vitacura', 'Puente Alto', 'Pirque', 'San José de Maipo', 'Colina', 'Lampa', 'TilVl', 'San Bernardo', 'Buin', 'Calera de Tango', 'Paine', 'Melipilla', 'Alhué', 'Curacaví', 'María Pinto', 'San Pedro', 'Talagante', 'El Monte', 'Isla de Maipo', 'Padre Hurtado', 'Peñaflor']),],
            'obs'         => 'string|max:1000',
            'persona_id'  => 'required|integer|exists:personas,id',
            
        ];
    }
}
